Bulky.Web/Areas/Admin/Controllers/CompanyController.cs
using Bulky.DataAccess.Data;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models.Models;
using Bulky.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bulky.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Company> companyList = _unitOfWork.Company.GetAll();

            return View(companyList);
        }
        public IActionResult Upsert(int id)
        {
           
            if (id == null || id == 0)
            {
                return View(new Company());
            }
            else
            {
                Company company= _unitOfWork.Company.Get(u => u.Id == id);
                return View(company);
            }

        }
        [HttpPost]
        public IActionResult Upsert(Company company)
        {
            if (ModelState.IsValid)
            {
                
                if(company.Id == 0)
                {
                    _unitOfWork.Company.Add(company);
                }
                else
                {
                    _unitOfWork.Company.Update(company);
                }
               
                _unitOfWork.Save();
                TempData["success"] = "The company has been created succesfully.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "";
            return View(company);
        }


        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> companyList = _unitOfWork.Company.GetAll().ToList();
            return Json(new { data = companyList });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var companyDelete = _unitOfWork.Company.Get(u=> u.Id == id);
            if(companyDelete == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
 

            _unitOfWork.Company.Remove(companyDelete);
            _unitOfWork.Save();

            List<Company> companyList = _unitOfWork.Company.GetAll().ToList();
            return Json(new { success = true, message = "Deleted succesfully" });
        }
        #endregion
    }
}

Bulky.Web/Areas/Admin/Controllers/ProductController.cs
using Bulky.DataAccess.Data;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models.Models;
using Bulky.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bulky.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Product> productList = _unitOfWork.Product.GetAll(includeProperties:"Category");

            return View(productList);
        }
        public IActionResult Upsert(int id)
        {
            ProductVm productVm = new()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
            };
            if (id == null || id == 0)
            {
                productVm.Product = new();
            }
            else
            {
                productVm.Product = _unitOfWork.Product.Get(u => u.Id == id);
            }

            return View(productVm);
        }
        [HttpPost]
        public IActionResult Upsert(ProductVm productVm, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    if (!string.IsNullOrEmpty(productVm.Product.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, productVm.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    productVm.Product.ImageUrl = @"\images\product\" + fileName;
                }
                if(productVm.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productVm.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(productVm.Product);
                }
               
                _unitOfWork.Save();
                TempData["success"] = "The Product has been created succesfully.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "";
            return View(productVm.Product);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> productList = _unitOfWork.Product.GetAll(includeProperties:"Category").ToList();
            return Json(new { data = productList });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var productDelete = _unitOfWork.Product.Get(u=> u.Id == id);
            if(productDelete == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, productDelete.ImageUrl.TrimStart('\\'));

            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Product.Remove(productDelete);
            _unitOfWork.Save();

            List<Product> productList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new { success = true, message = "Deleted succesfully" });
        }
        #endregion
    }
}

Bulky.Web/Areas/Admin/Views/Company/Index.cshtml
@model List<Company>

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Company List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Create New Company
            </a>
        </div>
    </div>
</div>


<table id="tblData" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Phone Number</th>
            <th></th>
        </tr>
    </thead>
</table>

@section Scripts
{
    <script src="~/js/company.js"></script>
}

Bulky.Web/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 my-4">
    <div class="card-header bg-primary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id == 0 ? "Create" : "Edit") Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body py-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div class="form-floating py-2 col-12">
                            <label asp-for="Name" class="p-0"></label>
                            <input asp-for="Name" type="text" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <label asp-for="PhoneNumber" class="p-0"></label>
                            <input asp-for="PhoneNumber" type="text" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <label asp-for="PostalCode" class="p-0"></label>
                            <input asp-for="PostalCode" type="text" class="form-control" />
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <label asp-for="State" class="p-0"></label>
                            <input asp-for="State" type="text" class="form-control" />
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>

                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Id == 0)
                                {
                                    <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
                                }

                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Product" asp-action="Index" class="btn btn-secondary" style="width:150px">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </form>
    </div>
    

</div>

@section Scripts
{
    <script>
        tinymce.init({
            selector: 'textarea#default',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage advtemplate ai mentions tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}